version: '3'

services:
  unifi-client-alerts:
    container_name: unificlientalerts
    image: zsamuels28/unificlientalerts:latest
    restart: unless-stopped
    environment:
      # UniFi Controller settings
      UNIFI_CONTROLLER_USER: ${UNIFI_CONTROLLER_USER}
      UNIFI_CONTROLLER_PASSWORD: ${UNIFI_CONTROLLER_PASSWORD}
      UNIFI_CONTROLLER_URL: ${UNIFI_CONTROLLER_URL}
      # UNIFI_SITE_ID: ${UNIFI_SITE_ID}
      # CONTROLLER_VERSION: ${UNIFI_CONTROLLER_VERSION}
      
      # General settings
      ALWAYS_NOTIFY: ${ALWAYS_NOTIFY:-false}
      REMEMBER_NEW_DEVICES: ${REMEMBER_NEW_DEVICES:-true}
      # KNOWN_MACS: ${KNOWN_MACS}
      # CHECK_INTERVAL: ${CHECK_INTERVAL}
      
      # Notification service selection
      NOTIFICATION_SERVICE: ${NOTIFICATION_SERVICE:-Telegram}
      
      # Telegram settings
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEPORT_NOTIFICATIONS: ${TELEPORT_NOTIFICATIONS:-false}
      
      # Ntfy settings
      # NTFY_URL: ${NTFY_URL}
      
      # Pushover settings
      # PUSHOVER_TOKEN: ${PUSHOVER_TOKEN}
      # PUSHOVER_USER: ${PUSHOVER_USER}
      # PUSHOVER_TITLE: ${PUSHOVER_TITLE}
      
      # Device removal settings
      REMOVE_OLD_DEVICES: ${REMOVE_OLD_DEVICES}
      REMOVE_DELAY: ${REMOVE_DELAY}
    volumes:
      - unifi_data:/usr/src/myapp

volumes:
  unifi_data:
