version: '3'
services:
  UniFiClientAlerts:
    image: zsamuels28/unificlientalerts:latest
    environment:
      UNIFI_CONTROLLER_USER: ${UNIFI_CONTROLLER_USER}
      UNIFI_CONTROLLER_PASSWORD: ${UNIFI_CONTROLLER_PASSWORD}
      UNIFI_CONTROLLER_URL: ${UNIFI_CONTROLLER_URL}
      UNIFI_SITE_ID: ${UNIFI_SITE_ID}
      KNOWN_MACS: ${KNOWN_MACS}
      CHECK_INTERVAL: ${CHECK_INTERVAL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      CONTROLLER_VERSION: ${UNIFI_CONTROLLER_VERSION}