version: '3'

services:
  unifi-client-alerts:
    container_name: unificlientalerts
    image: zsamuels28/unificlientalerts:latest
    restart: unless-stopped
    environment:
      # UniFi Controller settings
      UNIFI_CONTROLLER_USER: ${UNIFI_CONTROLLER_USER}
      UNIFI_CONTROLLER_PASSWORD: ${UNIFI_CONTROLLER_PASSWORD}
      UNIFI_CONTROLLER_URL: ${UNIFI_CONTROLLER_URL}
      #UNIFI_SITE_ID: ${UNIFI_SITE_ID} # Uncomment if site id is different than default
      #CONTROLLER_VERSION: ${UNIFI_CONTROLLER_VERSION}
      
      # General settings
      #ALWAYS_NOTIFY: ${ALWAYS_NOTIFY} # Default to false
      #REMEMBER_NEW_DEVICES: ${REMEMBER_NEW_DEVICES} # Default to true
      #KNOWN_MACS: ${KNOWN_MACS} # Uncomment to add known MAC Addresses separated by commas
      #CHECK_INTERVAL: ${CHECK_INTERVAL} # Uncomment for a check interval different than 60 seconds
      
      # Notification service selection
      #NOTIFICATION_SERVICE: ${NOTIFICATION_SERVICE} # Telegram or Ntfy or Pushover (Defaults to Telegram)
      
      # Telegram settings
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      #TELEPORT_NOTIFICATIONS: ${TELEPORT_NOTIFICATIONS} # Default to false
      
      # Ntfy settings
      #NTFY_URL: ${NTFY_URL} # Uncomment if using Ntfy.sh
      
      # Pushover settings
      #PUSHOVER_TOKEN: ${PUSHOVER_TOKEN} #Pushover app token (Uncomment if using Pushover)
      #PUSHOVER_USER: ${PUSHOVER_USER} #Pushover user token (Uncomment if using Pushover)
      #PUSHOVER_TITLE: ${PUSHOVER_TITLE} #Pushover message title (Uncomment if using Pushover)
      
      #Slack settings
      #SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL} # Uncomment if using Slack
      
      # Device removal settings
      REMOVE_OLD_DEVICES: ${REMOVE_OLD_DEVICES} #Remove devices that are no longer in Unifi client list  
      REMOVE_DELAY: ${REMOVE_DELAY} # How long after client disconnects to remove from known devices
    volumes:
      - unifi_data:/usr/src/myapp

volumes:
  unifi_data:
