version: '3'
services:
  UniFiClientAlerts:
    image: zsamuels28/unificlientalerts:latest
    environment:
      UNIFI_CONTROLLER_USER: ${UNIFI_CONTROLLER_USER}
      UNIFI_CONTROLLER_PASSWORD: ${UNIFI_CONTROLLER_PASSWORD}
      UNIFI_CONTROLLER_URL: ${UNIFI_CONTROLLER_URL}
      #UNIFI_SITE_ID: ${UNIFI_SITE_ID} # Uncomment if site id is different than default
      #KNOWN_MACS: ${KNOWN_MACS} # Uncomment to add known MAC Addresses separated by commas
      #CHECK_INTERVAL: ${CHECK_INTERVAL} # Uncomment for a check interval different than 60 seconds
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      #NTFY_URL: ${NTFY_URL} # Uncomment if using Ntfy.sh
      #NOTIFICATION_SERVICE: ${NOTIFICATION_SERVICE} # Telegram or Ntfy (Defaults to Telegram)
      #CONTROLLER_VERSION: ${UNIFI_CONTROLLER_VERSION}