name: Update README with Version

on:
  push:
    branches:
      - main
    paths:
      - 'version'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from file
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          VERSION=$(cat version)
          sed -i "s/badge\/version-.*-blue/badge\/version-$VERSION-blue/" README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          if git diff --exit-code README.md; then
            echo "No changes to the README"
            exit 0
          fi
          git add README.md
          git commit -m "Update README with new version $VERSION"
          git push
